Mobile and desktop version pull request
Muhammad-UsmanTariq/Mobile-Portfolio pull request #4
Opened 2023-08-02 13:06 UTC by Muhammad-UsmanTariq

### I complete this  mobile and desktop project using css and html according to the given conditions.

- [x]  Use media queries to make it responsive for desktop version.
- [x] Use grid and flexbox.
- [x] No use of javascript in this project.

2023-08-04 11:25 UTC, emhamza requested changes
Hi @Muhammad-UsmanTariq 🎉 

Good job so far 👍 There is still something that you need to update in order to go to the next project

![tnnd-the-noise-next-door](https://github.com/Muhammad-UsmanTariq/Mobile-Portfolio/assets/122353030/a3d9c563-ee8c-4a85-9e39-33292d6b4da7)

2023-08-04 11:25 UTC, emhamza commented on index.css
> +  }
@Muhammad-UsmanTariq I would suggest you to have look on your background img and make it similar to Figma design: 
![osman style](https://github.com/Muhammad-UsmanTariq/Mobile-Portfolio/assets/122353030/55a1633c-8e3e-4316-9ef0-765e549957e3)

2023-08-04 13:53 UTC, Muhammad-UsmanTariq commented on index.css
> +  }
### First my portfolio background is this

![back](https://github.com/Muhammad-UsmanTariq/Mobile-Portfolio/assets/138443733/fb2686f6-eb79-45d2-84aa-b521a244b120)

2023-08-04 13:57 UTC, Muhammad-UsmanTariq commented on index.css
> +  }
### Now i fix it.

![Screenshot 2023-08-04 184203](https://github.com/Muhammad-UsmanTariq/Mobile-Portfolio/assets/138443733/a5d41cab-1e93-4d87-8062-ccc2ef5de495)

2023-08-04 13:59 UTC, Muhammad-UsmanTariq commented on index.css
> +  }
body {
    margin: 0;
    padding: 0;
  }
These lines are extar so i removed it from the code.

2023-08-07 06:11 UTC, emhamza approved these changes
Hi @Muhammad-UsmanTariq 💚 

Good job implementing the changes, there is nothing to say
**Your Project is Approved:**

 
![appr](https://github.com/Muhammad-UsmanTariq/Mobile-Portfolio/assets/122353030/a1b52d56-ad56-4a21-81d4-36615f2d8203)

2023-08-07 06:13 UTC, merged